### PR TITLE
check changed/new docstrings

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Review by bernt-matthias — APPROVED** [review]
Looks good to me. But in the end I guess we need to see this in action.

Can you remove the installation of numpy in travis.yml and maybe use the pypi package of CTDopts (instead of the github link).

**Comment by mr-c** [comment]
```
~/ctd2cwl/CTDConverter$ make diff_pydocstyle_report 
pydocstyle setup.py setup.py ctdconverter/convert.py ctdconverter/common/exceptions.py ctdconverter/common/__init__.py ctdconverter/common/logger.py ctdconverter/common/utils.py ctdconverter/__init__.py ctdconverter/cwl/__init__.py ctdconverter/cwl/converter.py ctdconverter/galaxy/__init__.py ctdconverter/galaxy/converter.py > pydocstyle_report.txt 2>&1 || true
diff-quality --compare-branch=master --violations=pydocstyle --fail-under=100 pydocstyle_report.txt
-------------
Diff Quality
Quality Report: pydocstyle
Diff: master...HEAD, staged and unstaged changes
-------------
ctdconverter/cwl/converter.py (100%)
-------------
Total:   1 line
Violations: 0 lines
% Quality: 100%
-------------
```

**Review by bernt-matthias — APPROVED** [review]

**Comment by mr-c** [comment]
> maybe use the pypi package of CTDopts (instead of the github link).

There is no pypi package for ctdopts: https://github.com/WorkflowConversion/CTDopts/issues/26

**Comment by bernt-matthias** [comment]
> There is no pypi package for ctdopts: WorkflowConversion/CTDopts#26

Ups. True. Forgot that I constructed the conda package directly from the releases.

**Pull request merged**
