### PR TITLE
test data

### PR DESCRIPTION
**Pull request by bernt-matthias**
this adds test CTD files for string, int, float, select parameters which might be a starting point for unit tests and improving the generated xml files

xml files are generated by: `python CTDConverter/convert.py galaxy -i CTDConverter/test-data/*ctd -o CTDConverter/test-data -m ../macros.xml  -b version`

missing are at the moment at least files for input and output file parameters.

TODOs:
- [x] add ITEMLIST tests
- [x] fix xsd version and link in test ctd files (https://github.com/OpenMS/OpenMS/issues/4174)
- [ ] switch back to CTDopts development branch in `.travis.yml` after https://github.com/WorkflowConversion/CTDopts/pull/19 is merged

### CODE REVIEW

**Comment by Tomnl** [comment]
Hi @bernt-matthias,

Thanks for this. I written a few basic unit-tests to cover the data, should I contribute the unit-tests to this fork? 

Also, on my local system when I run `python CTDConverter/convert.py galaxy -i CTDConverter/test-data/*ctd -o CTDConverter/test-data -m ../macros.xml -b version` I do not get the "[CDATA[" added to Galaxy XML tools. 

e.g.
In the data you have provided 

```
<description><![CDATA[String parameter tests]]></description>
```
But in my local convert I get just

```
<description>String parameter tests</description>
```

Any idea why?

**Comment by bernt-matthias** [comment]
Maybe I did something wrong. Have to check later. Having a 1st unit test here seems useful.

**Comment by Tomnl** [comment]
hi @bernt-matthias,

I have made a pull request to your fork of this with the unit-tests added

**Comment by bernt-matthias** [comment]
Will take care of this next week. Thanks..

**Comment by bernt-matthias** [comment]
Seems that this https://github.com/WorkflowConversion/CTDopts/pull/19  is required to get a step further toward passing tests. 

@mr-c any ideas how to continue here -- strategically? Would be great to continue here since we have some momentum at the moment (pun not intended...)

**Comment by bernt-matthias** [comment]
@Tomnl: hooray, tests are passing (the problem was that the xmls were generated on another branch). Will now add file input/output ctds (and whatever else is missing...)

**Comment by Tomnl** [comment]
Great!

**Pull request closed without merging**
