### PR TITLE
WIP: fix layout of package

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Hey @mr-c can you allow me to push here? Or should I open a PR to this branch?

**Comment by mr-c** [comment]
Hey @bernt-matthias I don't have the ability to give you `write` access here (yet). Perhaps @timosachsenberg or @jpfeuffer can do so

If you don't want to wait, you can open a PR to this branch, yes

**Comment by jpfeuffer** [comment]
@bernt-matthias You should have an invitation.

**Comment by bernt-matthias** [comment]
Thanks @jpfeuffer . Works.

**Pull request merged**
